#+TITLE: Seminar on Reinforcement Learning and Decision Making Under Uncertainty
#+AUTHOR: Christos Dimitrakakis
#+EMAIL:christos.dimitrakakis@unine.ch
#+LaTeX_HEADER: \newcommand \E {\mathop{\mbox{\ensuremath{\mathbb{E}}}}\nolimits}
#+LaTeX_HEADER: \newcommand\ind[1]{\mathop{\mbox{\ensuremath{\mathbb{I}}}}\left\{#1\right\}}
#+LaTeX_HEADER: \renewcommand \Pr {\mathop{\mbox{\ensuremath{\mathbb{P}}}}\nolimits}
#+LaTeX_HEADER: \DeclareMathOperator*{\argmax}{arg\,max}
#+LaTeX_HEADER: \DeclareMathOperator*{\argmin}{arg\,min}
#+LaTeX_HEADER: \newcommand \defn {\mathrel{\triangleq}}
#+LaTeX_HEADER: \newcommand \Reals {\mathbb{R}}
#+LaTeX_HEADER: \newcommand \Param {\Theta}
#+LaTeX_HEADER: \newcommand \param {\theta}
#+LaTeX_HEADER: \newcommand \pol {\pi}
#+LaTeX_HEADER: \newcommand \mdp {\mu}
#+LaTeX_HEADER: \newcommand \bel {\xi}
#+TAGS: activity advanced definition exercise homework project example theory code
#+OPTIONS:   H:2

* Expected Utility Hypothesis and the Measurability of Utility

- Initially people thought decisions under risk and no risk were different.
- Can we justify choices under risk through expected utility?
- Is there an axiomatic justification?
- Can utility be measured?

- Final outcomes: $x_1, \ldots, x_n$  in $X$.
- Probability distributions $F$ so that for any $f \in F$, $f_i$ is the probability of $x_i$.
- $f \geq g$ means 'f is not preferred to g'

The postulates are:

P1. Perfect linear order

- 1. Universality: $f \geq h$ or $h \geq f$.
- 2. Transitivity: If $f \leq g$ and $g \leq h$ then $f \leq h$.

P2. Continuity

If $af + (1 - a)h \leq g$ for all $a \in [0,1)$ then $f \leq g$.

P3. If $a \in (0,1)$, $af + (1 - a)h \leq ag + (1 - a)h \Leftrightarrow f \leq g$.

From the above postulates, the expected utility hypothesis follows.

If we assume a perfect linear order, then of course any function
$U(f)$ such that $U(f) > U(g)$ implies $f > g$ will be enough.
Any monotonic transform of that function will also be enough. 

However, we can look at a special function $C$ such that
\[
U(f) = E_f[C] = \sum_x C(x) P_f(x)
\]

The paper does not really prove or disprove that the expected utility
hypothesis. There are actually experiments which we can run that do
so, but they are only obliquely referred to by this paper.


* Fairness, matching and regret

** What kind of guarantees can we have on matchings?
*** Stability
*** Social welfare
*** Fairness
*** Envy-freenes
*** Strategyproofness

Agents $i \in [N]$, $j \in [L]$.

We define agents' preferences $u_t$ at time $t$ with matching function
$M$. When agents are selected, they obtain reward $r_{t,i} = X(i, j) \sim
P_{i,j}$. They also introduce a cost function so that
$c_{t,i} = C(i, j, u_t)$ is the cost incurred and
$\tau_{t,i} = T(i, j, u_t)$ is the 

The total payoff is
\[
R_{t,i}(i,j) = r_{t,i} - c_{t,i} + \tau_{t,i}
\]

Most of the work has thus focused on the pure bandit setting. However,
we will look at more structured settings.
